/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Health check function exposed to Node.js.
 *
 * # Returns
 * Always returns "ok" to indicate the native module is loaded and functional
 */
export declare function ping(): string
/**
 * Sets the application configuration for automation.
 *
 * # Arguments
 * * `executable` - Path to the executable to launch
 * * `class_names` - List of window class names to search for interactive elements
 */
export declare function setAppConfig(executable: string, classNames: Array<string>): void
/**
 * Launches a Windows executable and returns its process ID.
 *
 * # Arguments
 * * `executable_path` - Optional full path to the executable to launch. If None, uses the configured executable.
 *
 * # Returns
 * A `Result` containing the process ID, or error if the process cannot be spawned
 */
export declare function launch(executablePath?: string | undefined | null): Promise<number>
/**
 * Discovers all top-level visible windows for a given process.
 *
 * Uses a multi-strategy approach:
 * 1. UIAutomation discovery (most reliable for modern apps)
 * 2. Direct Win32 EnumWindows enumeration
 *
 * # Arguments
 * * `process_id` - The process ID to query
 *
 * # Returns
 * A `Result` containing a vector of window handles as strings
 */
export declare function enumerateWindows(processId: number): Promise<Array<string>>
/**
 * Locates an interactive element within a window.
 *
 * # Arguments
 * * `window_handle` - String representation of the window handle
 * * `class_names` - Optional list of class names to search for. If None, uses configured class names.
 * * `_automation_id` - (Unused) Automation ID for element lookup
 * * `_name` - (Unused) Name property for element lookup
 * * `_role` - (Unused) Role property for element lookup
 *
 * # Returns
 * A `Result` containing `Some(handle)` if an element is found, or `None` as fallback
 */
export declare function findElement(windowHandle: string, classNames?: Array<string> | undefined | null, automationId?: string | undefined | null, name?: string | undefined | null, role?: string | undefined | null): Promise<string | null>
/**
 * Sets text content of a window element using the WM_SETTEXT message.
 *
 * Sends a Windows message to set the text of the target window/control.
 * This is a synchronous operation at the Windows message level.
 *
 * # Arguments
 * * `element_handle` - String representation of the target element's window handle
 * * `text` - The text content to set
 *
 * # Returns
 * A `Result` that resolves when the message is processed
 */
export declare function typeText(elementHandle: string, text: string): Promise<void>
/**
 * Moves the mouse cursor to hover over an element.
 *
 * # Arguments
 * * `element_handle` - String representation of the target element's window handle
 *
 * # Returns
 * A `Result` that resolves when the hover operation is complete
 */
export declare function hoverElement(elementHandle: string): Promise<void>
/**
 * Scrolls an element in the specified direction.
 *
 * # Arguments
 * * `element_handle` - String representation of the target element's window handle
 * * `direction` - Direction to scroll: "up", "down", "left", "right"
 * * `amount` - Number of scroll units (typically 1-3 for smooth scrolling)
 *
 * # Returns
 * A `Result` that resolves when the scroll operation is complete
 */
export declare function scrollElement(elementHandle: string, direction: string, amount: number): Promise<void>
/**
 * Performs a drag and drop operation from one element to another.
 *
 * # Arguments
 * * `from_element_handle` - String representation of the source element's window handle
 * * `to_element_handle` - String representation of the target element's window handle
 *
 * # Returns
 * A `Result` that resolves when the drag and drop operation is complete
 */
export declare function dragDrop(fromElementHandle: string, toElementHandle: string): Promise<void>
