/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'win-auto-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.android-arm64.node')
          } else {
            nativeBinding = require('win-auto-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'win-auto-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('win-auto-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'win-auto-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('win-auto-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'win-auto-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('win-auto-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'win-auto-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('win-auto-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'win-auto-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./win-auto-native.darwin-universal.node')
      } else {
        nativeBinding = require('win-auto-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'win-auto-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.darwin-x64.node')
          } else {
            nativeBinding = require('win-auto-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'win-auto-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.darwin-arm64.node')
          } else {
            nativeBinding = require('win-auto-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'win-auto-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./win-auto-native.freebsd-x64.node')
      } else {
        nativeBinding = require('win-auto-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('win-auto-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('win-auto-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('win-auto-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('win-auto-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('win-auto-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('win-auto-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('win-auto-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('win-auto-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'win-auto-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('win-auto-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { setAppConfig, debugDiscovery, launch, ping, enumerateWindows, closeApp, closeWindow, isProcessRunning, findElement, typeText, sendKeys, getText, findElementName, hoverElement, scrollElement, dragDrop, captureScreenshot, captureScreenshotToFile } = nativeBinding

module.exports.setAppConfig = setAppConfig
module.exports.debugDiscovery = debugDiscovery
module.exports.launch = launch
module.exports.ping = ping
module.exports.enumerateWindows = enumerateWindows
module.exports.closeApp = closeApp
module.exports.closeWindow = closeWindow
module.exports.isProcessRunning = isProcessRunning
module.exports.findElement = findElement
module.exports.typeText = typeText
module.exports.sendKeys = sendKeys
module.exports.getText = getText
module.exports.findElementName = findElementName
module.exports.hoverElement = hoverElement
module.exports.scrollElement = scrollElement
module.exports.dragDrop = dragDrop
module.exports.captureScreenshot = captureScreenshot
module.exports.captureScreenshotToFile = captureScreenshotToFile
