/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function setAppConfig(executable: string, classNames: Array<string>): void
export interface DialogInfo {
  handle: string
  title: string
  className: string
  visible: boolean
  /** "standard" for #32770, "directui" for DirectUIHWND, "uwp" for Windows.UI.Core.CoreWindow */
  dialogType: string
}
export declare function detectDialogType(windowHandle: string): string
export interface DialogControl {
  handle: string
  name: string
  controlType: string
}
export declare function findDialogs(processId: number): Array<DialogInfo>
export declare function getDialogControls(windowHandle: string): Array<DialogControl>
export declare function clickDialogButton(windowHandle: string, buttonText: string): Promise<void>
export declare function setDialogFilePath(windowHandle: string, path: string): Promise<void>
export interface WindowDebugInfo {
  hwnd: string
  pid: number
  className: string
  title: string
  visible: boolean
  ownerInvalid: boolean
  matchesTargetPid: boolean
  passesTopLevelVisible: boolean
  processImage: string
}
export declare function debugDiscovery(processId: number): Array<WindowDebugInfo>
/** HWND tree node for the legacy/raw Win32 hierarchy inspector */
export interface HwndNode {
  handle: string
  className: string
  title: string
  visible: boolean
  children: Array<HwndNode>
}
/**
 * Inspects the raw Win32 HWND tree under a given window handle.
 * Unlike inspectWindowTree (which uses UIA), this shows the real HWND
 * hierarchy with class names and window text — essential for legacy app debugging.
 */
export declare function inspectHwndTree(windowHandle: string, maxDepth?: number | undefined | null): Array<HwndNode>
/**
 * Detailed Win32 legacy info about a window handle.
 * Returns className, text, style, exStyle, pid, threadId, isUnicode,
 * parentHwnd, ownerHwnd, dpi.
 */
export interface WindowInfo {
  className: string
  text: string
  style: number
  exStyle: number
  pid: number
  threadId: number
  isUnicode: boolean
  parentHwnd: string
  ownerHwnd: string
  dpi: number
}
export declare function getWindowInfo(windowHandle: string): WindowInfo
export interface WinEventInfo {
  eventType: number
  hwnd: string
  idObject: number
  idChild: number
  idEventThread: number
  timestamp: number
}
/**
 * Blocks for up to `timeout_ms` waiting for a UI event.
 * Returns `true` if a change was detected, `false` on timeout.
 */
export declare function waitForUiChange(timeoutMs: number): Promise<boolean>
/**
 * Start the WinEvent watcher with a JS callback invoked on each WinEvent.
 * The callback receives a WinEventInfo object. Call `stopWinEventWatcher`
 * to unregister the callback. The underlying hook thread runs for the
 * lifetime of the process (or until stopWinEventWatcher is called).
 */
export declare function startWinEventWatcher(callback: (...args: any[]) => any): void
/**
 * Unregister the WinEvent JS callback. The underlying hook thread continues
 * running (for `waitForUiChange`), but no further JS callbacks are made.
 */
export declare function stopWinEventWatcher(): void
/**
 * Send a WM_COMMAND message to a window (for legacy controls that only
 * respond to Win32 messages, not UIA).
 */
export declare function sendWmCommand(windowHandle: string, controlId: number, commandId: number): void
/** Send a WM_SETTEXT message to set the text of a control (legacy fallback). */
export declare function sendWmSetText(controlHandle: string, text: string): void
/** Send a WM_NOTIFY message to a window (for legacy control notifications). */
export declare function sendWmNotify(windowHandle: string, controlId: number, notificationCode: number): void
export const enum InputMode {
  /** Use UIA patterns only – fail if pattern is unavailable. */
  Pattern = 0,
  /** Use Win32 / SendInput hardware simulation only. */
  Hardware = 1,
  /** Try pattern first, fall back to hardware on PatternNotSupported. */
  Auto = 2
}
export declare function expandCollapseExpand(elementHandle: string): void
export declare function expandCollapseCollapse(elementHandle: string): void
/**
 * ScrollAmount enum values mapped from windows-rs UIA ScrollAmount:
 *   0 = LargeDecrement, 1 = SmallDecrement, 2 = NoAmount, 3 = LargeIncrement, 4 = SmallIncrement
 */
export declare function scrollPatternScroll(elementHandle: string, horizontalAmount: number, verticalAmount: number): void
export declare function scrollPatternSetScrollPercent(elementHandle: string, horizontalPercent: number, verticalPercent: number): void
export declare function rangeValueGetValue(elementHandle: string): number
export declare function rangeValueSetValue(elementHandle: string, value: number): void
/** WindowVisualState enum values: 0 = Normal, 1 = Maximized, 2 = Minimized */
export declare function windowPatternSetVisualState(elementHandle: string, state: number): void
export declare function windowPatternWaitForInputIdle(elementHandle: string, timeoutMs: number): boolean
export declare function selectionGetSelection(elementHandle: string): Array<string>
/** Returns the row count for a grid element. */
export declare function gridGetRowCount(elementHandle: string): number
/** Returns the column count for a grid element. */
export declare function gridGetColumnCount(elementHandle: string): number
/** Returns the element handle at the specified row and column in a grid. */
export declare function gridGetItem(elementHandle: string, row: number, column: number): string
/** Returns row header element handles for a table element. */
export declare function tableGetRowHeaders(elementHandle: string): Array<string>
/** Returns column header element handles for a table element. */
export declare function tableGetColumnHeaders(elementHandle: string): Array<string>
export declare function selectionItemSelect(elementHandle: string): void
export declare function selectionItemAddToSelection(elementHandle: string): void
export declare function selectionItemRemoveFromSelection(elementHandle: string): void
export declare function selectionItemIsSelected(elementHandle: string): boolean
export declare function highlightElement(elementHandle: string, color?: string | undefined | null, durationMs?: number | undefined | null): Promise<void>
export declare function findElement(windowHandle: string, classNames?: Array<string> | undefined | null, automationId?: string | undefined | null, name?: string | undefined | null, role?: string | undefined | null, className?: string | undefined | null, text?: string | undefined | null, matchMode?: string | undefined | null): Promise<string | null>
export declare function typeText(elementHandle: string, text: string): Promise<void>
export declare function sendKeys(elementHandle: string, text: string): Promise<void>
export declare function pressKeyCodes(windowHandle: string, keyCodes: Array<number>): Promise<void>
export declare function getText(elementHandle: string): Promise<string>
export declare function findElementName(windowHandle: string, name: string): Promise<string | null>
export declare function clickElement(elementHandle: string): Promise<void>
export declare function clickElementByName(windowHandle: string, name: string): Promise<void>
/**
 * Clicks a sequence of elements by name in a single UIA tree traversal.
 * This is much faster than calling clickElementByName N times because
 * it only enumerates the UIA tree once instead of N times.
 */
export declare function clickSequence(windowHandle: string, names: Array<string>): Promise<void>
export interface ElementPathStep {
  role: string
  name: string
  automationId: string
  className: string
  siblingIndex: number
}
export declare function buildElementPath(elementHandle: string): Array<ElementPathStep>
export declare function resolveElementPath(windowHandle: string, path: Array<ElementPathStep>): Promise<string | null>
export declare function hoverElement(elementHandle: string): Promise<void>
export declare function scrollElement(elementHandle: string, direction: string, amount: number): Promise<void>
export declare function getValue(elementHandle: string): Promise<string>
export declare function setValue(elementHandle: string, value: string): Promise<void>
export declare function selectElement(elementHandle: string): Promise<void>
export declare function toggleElement(elementHandle: string): Promise<void>
export declare function getToggleState(elementHandle: string): Promise<string>
export declare function findAll(windowHandle: string, classNames?: Array<string> | undefined | null, automationId?: string | undefined | null, name?: string | undefined | null, role?: string | undefined | null, className?: string | undefined | null, text?: string | undefined | null, matchMode?: string | undefined | null): Promise<Array<string>>
export declare function getParent(elementHandle: string): Promise<string | null>
export declare function getChildren(elementHandle: string): Promise<Array<string>>
export declare function getSiblings(elementHandle: string): Promise<Array<string>>
export declare function isVisible(elementHandle: string): Promise<boolean>
export declare function isEnabled(elementHandle: string): Promise<boolean>
export declare function isFocused(elementHandle: string): Promise<boolean>
export declare function focusElement(elementHandle: string): Promise<void>
export interface WindowBounds {
  left: number
  top: number
  width: number
  height: number
}
export declare function getWindowBounds(windowHandle: string): Promise<WindowBounds>
export declare function setWindowBounds(windowHandle: string, left: number, top: number, width: number, height: number): Promise<void>
export declare function focusWindow(windowHandle: string): Promise<void>
export declare function maximizeWindow(windowHandle: string): Promise<void>
export declare function minimizeWindow(windowHandle: string): Promise<void>
export declare function restoreWindow(windowHandle: string): Promise<void>
export declare function pressKey(windowHandle: string, keyCombination: string): Promise<void>
export declare function rightClickElement(elementHandle: string): Promise<void>
export declare function doubleClickElement(elementHandle: string): Promise<void>
export declare function mouseMove(x: number, y: number): Promise<void>
export declare function clickAt(x: number, y: number): Promise<void>
export declare function keyDown(windowHandle: string, key: string): Promise<void>
export declare function keyUp(windowHandle: string, key: string): Promise<void>
export declare function selectText(elementHandle: string): Promise<void>
export declare function getSelection(elementHandle: string): Promise<string>
export declare function replaceSelectedText(elementHandle: string, text: string): Promise<void>
export interface ElementNode {
  handle: string
  name: string
  role: string
  automationId: string
  isVisible: boolean
  isEnabled: boolean
  children: Array<ElementNode>
}
export declare function inspectWindowTree(windowHandle: string, maxDepth?: number | undefined | null): Array<ElementNode>
export declare function getElementAttribute(elementHandle: string, attributeName: string): Promise<string>
export declare function dragDrop(fromElementHandle: string, toElementHandle: string): Promise<void>
export interface LaunchOptions {
  args?: Array<string>
  cwd?: string
  env?: Array<string>
  /** If "admin", spawn the process elevated (triggers UAC prompt). */
  runAs?: string
  /** Attach process to a job object so it's killed when the parent exits. */
  job?: boolean
  /** If true, don't create a console window (DETACHED_PROCESS). */
  createNoWindow?: boolean
  /** AUMID for UWP app activation (alternative to executablePath). */
  aumid?: string
}
/**
 * High-level launch — replaces the old `std::process::Command` approach.
 * Returns the PID of the spawned process (or the window-owning PID for
 * ApplicationFrameHost scenarios).
 */
export declare function launch(executablePath?: string | undefined | null, classNames?: Array<string> | undefined | null): Promise<number>
/** Full-featured launch with options (args, cwd, env). */
export declare function launchProcess(executablePath: string, options?: LaunchOptions | undefined | null): Promise<number>
/** Health check function exposed to Node.js. */
export declare function ping(): string
/** Discovers windows for a process and returns handles as strings. */
export declare function enumerateWindows(processId: number, executable?: string | undefined | null): Promise<Array<string>>
export declare function closeApp(processId: number): Promise<void>
export declare function closeWindow(windowHandle: string): Promise<void>
export declare function isProcessRunning(processId: number): boolean
export interface ProcessEntry {
  pid: number
  imageName: string
}
export declare function findProcessesByName(imageName: string): Array<ProcessEntry>
export declare function waitForProcessExit(processId: number, timeoutMs: number): Promise<boolean>
export declare function getProcessImageName(processId: number): string
export declare function killProcess(processId: number): void
export declare function isProcessElevated(processId: number): boolean
/**
 * Launch a process elevated (admin) via ShellExecuteExW with "runas" verb.
 * Returns the PID of the spawned process.
 */
export declare function runElevated(executablePath: string, args?: Array<string> | undefined | null, cwd?: string | undefined | null): Promise<number>
/**
 * Launch a UWP app by its AUMID (Application User Model ID) using
 * IApplicationActivationManager::ActivateApplication.
 * Returns the PID of the activated process.
 */
export declare function launchAppByAumid(aumid: string): number
export declare function captureScreenshot(elementHandle: string): Promise<Array<number>>
export declare function captureScreenshotToFile(elementHandle: string, path: string): Promise<void>
export interface ImageMatch {
  x: number
  y: number
  width: number
  height: number
  confidence: number
}
export declare function findImage(elementHandle: string, template: Array<number>): Promise<ImageMatch | null>
