/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function setAppConfig(executable: string, classNames: Array<string>): void
export interface DialogInfo {
  handle: string
  title: string
  className: string
  visible: boolean
}
export interface DialogControl {
  handle: string
  name: string
  controlType: string
}
export declare function findDialogs(processId: number): Array<DialogInfo>
export declare function getDialogControls(windowHandle: string): Array<DialogControl>
export declare function clickDialogButton(windowHandle: string, buttonText: string): Promise<void>
export declare function setDialogFilePath(windowHandle: string, path: string): Promise<void>
export interface WindowDebugInfo {
  hwnd: string
  pid: number
  className: string
  title: string
  visible: boolean
  ownerInvalid: boolean
  matchesTargetPid: boolean
  passesTopLevelVisible: boolean
  processImage: string
}
export declare function debugDiscovery(processId: number): Array<WindowDebugInfo>
/** HWND tree node for the legacy/raw Win32 hierarchy inspector */
export interface HwndNode {
  handle: string
  className: string
  title: string
  visible: boolean
  children: Array<HwndNode>
}
/**
 * Inspects the raw Win32 HWND tree under a given window handle.
 * Unlike inspectWindowTree (which uses UIA), this shows the real HWND
 * hierarchy with class names and window text — essential for legacy app debugging.
 */
export declare function inspectHwndTree(windowHandle: string, maxDepth?: number | undefined | null): Array<HwndNode>
export interface WinEventInfo {
  eventType: number
  hwnd: string
  idObject: number
  idChild: number
  idEventThread: number
  timestamp: number
}
/**
 * Blocks for up to `timeout_ms` waiting for a UI event.
 * Returns `true` if a change was detected, `false` on timeout.
 */
export declare function waitForUiChange(timeoutMs: number): Promise<boolean>
/**
 * Start the WinEvent watcher with a JS callback invoked on each WinEvent.
 * The callback receives a WinEventInfo object. Call `stopWinEventWatcher`
 * to unregister the callback. The underlying hook thread runs for the
 * lifetime of the process (or until stopWinEventWatcher is called).
 */
export declare function startWinEventWatcher(callback: (...args: any[]) => any): void
/**
 * Unregister the WinEvent JS callback. The underlying hook thread continues
 * running (for `waitForUiChange`), but no further JS callbacks are made.
 */
export declare function stopWinEventWatcher(): void
export declare function highlightElement(elementHandle: string, color?: string | undefined | null, durationMs?: number | undefined | null): Promise<void>
export declare function findElement(windowHandle: string, classNames?: Array<string> | undefined | null, automationId?: string | undefined | null, name?: string | undefined | null, role?: string | undefined | null, className?: string | undefined | null, text?: string | undefined | null, matchMode?: string | undefined | null): Promise<string | null>
export declare function typeText(elementHandle: string, text: string): Promise<void>
export declare function sendKeys(elementHandle: string, text: string): Promise<void>
export declare function pressKeyCodes(windowHandle: string, keyCodes: Array<number>): Promise<void>
export declare function getText(elementHandle: string): Promise<string>
export declare function findElementName(windowHandle: string, name: string): Promise<string | null>
export declare function clickElement(elementHandle: string): Promise<void>
export declare function clickElementByName(windowHandle: string, name: string): Promise<void>
/**
 * Clicks a sequence of elements by name in a single UIA tree traversal.
 * This is much faster than calling clickElementByName N times because
 * it only enumerates the UIA tree once instead of N times.
 */
export declare function clickSequence(windowHandle: string, names: Array<string>): Promise<void>
export interface ElementPathStep {
  role: string
  name: string
  automationId: string
  className: string
  siblingIndex: number
}
export declare function buildElementPath(elementHandle: string): Array<ElementPathStep>
export declare function resolveElementPath(windowHandle: string, path: Array<ElementPathStep>): Promise<string | null>
export declare function hoverElement(elementHandle: string): Promise<void>
export declare function scrollElement(elementHandle: string, direction: string, amount: number): Promise<void>
export declare function getValue(elementHandle: string): Promise<string>
export declare function setValue(elementHandle: string, value: string): Promise<void>
export declare function selectElement(elementHandle: string): Promise<void>
export declare function toggleElement(elementHandle: string): Promise<void>
export declare function getToggleState(elementHandle: string): Promise<string>
export declare function findAll(windowHandle: string, classNames?: Array<string> | undefined | null, automationId?: string | undefined | null, name?: string | undefined | null, role?: string | undefined | null, className?: string | undefined | null, text?: string | undefined | null, matchMode?: string | undefined | null): Promise<Array<string>>
export declare function getParent(elementHandle: string): Promise<string | null>
export declare function getChildren(elementHandle: string): Promise<Array<string>>
export declare function getSiblings(elementHandle: string): Promise<Array<string>>
export declare function isVisible(elementHandle: string): Promise<boolean>
export declare function isEnabled(elementHandle: string): Promise<boolean>
export declare function isFocused(elementHandle: string): Promise<boolean>
export declare function focusElement(elementHandle: string): Promise<void>
export interface WindowBounds {
  left: number
  top: number
  width: number
  height: number
}
export declare function getWindowBounds(windowHandle: string): Promise<WindowBounds>
export declare function setWindowBounds(windowHandle: string, left: number, top: number, width: number, height: number): Promise<void>
export declare function focusWindow(windowHandle: string): Promise<void>
export declare function maximizeWindow(windowHandle: string): Promise<void>
export declare function minimizeWindow(windowHandle: string): Promise<void>
export declare function restoreWindow(windowHandle: string): Promise<void>
export declare function pressKey(windowHandle: string, keyCombination: string): Promise<void>
export declare function rightClickElement(elementHandle: string): Promise<void>
export declare function doubleClickElement(elementHandle: string): Promise<void>
export declare function mouseMove(x: number, y: number): Promise<void>
export declare function clickAt(x: number, y: number): Promise<void>
export declare function keyDown(windowHandle: string, key: string): Promise<void>
export declare function keyUp(windowHandle: string, key: string): Promise<void>
export declare function selectText(elementHandle: string): Promise<void>
export declare function getSelection(elementHandle: string): Promise<string>
export declare function replaceSelectedText(elementHandle: string, text: string): Promise<void>
export interface ElementNode {
  handle: string
  name: string
  role: string
  automationId: string
  isVisible: boolean
  isEnabled: boolean
  children: Array<ElementNode>
}
export declare function inspectWindowTree(windowHandle: string, maxDepth?: number | undefined | null): Array<ElementNode>
export declare function getElementAttribute(elementHandle: string, attributeName: string): Promise<string>
export declare function dragDrop(fromElementHandle: string, toElementHandle: string): Promise<void>
export declare function gridGetRowCount(elementHandle: string): number
export declare function gridGetColumnCount(elementHandle: string): number
export declare function gridGetItem(elementHandle: string, row: number, column: number): string
export declare function tableGetRowHeaders(elementHandle: string): Array<string>
export declare function tableGetColumnHeaders(elementHandle: string): Array<string>
export declare function selectionItemSelect(elementHandle: string): void
export declare function selectionItemAddToSelection(elementHandle: string): void
export declare function selectionItemRemoveFromSelection(elementHandle: string): void
export declare function selectionItemIsSelected(elementHandle: string): boolean
export declare function launch(executablePath?: string | undefined | null, classNames?: Array<string> | undefined | null): Promise<number>
export interface LaunchOptions {
  args?: Array<string> | undefined | null
  cwd?: string | undefined | null
  env?: Array<string> | undefined | null
  /** If "admin", spawn the process elevated (triggers UAC prompt). */
  runAs?: string | undefined | null
}
export declare function launchProcess(executablePath: string, options?: LaunchOptions | undefined | null): Promise<number>
/** Health check function exposed to Node.js. */
export declare function ping(): string
/** Discovers windows for a process and returns handles as strings. */
export declare function enumerateWindows(processId: number, executable?: string | undefined | null): Promise<Array<string>>
export declare function closeApp(processId: number): Promise<void>
export declare function closeWindow(windowHandle: string): Promise<void>
export declare function isProcessRunning(processId: number): boolean
export interface ProcessEntry {
  pid: number
  imageName: string
}
export declare function findProcessesByName(imageName: string): Array<ProcessEntry>
export declare function waitForProcessExit(processId: number, timeoutMs: number): Promise<boolean>
export declare function getProcessImageName(processId: number): string
export declare function killProcess(processId: number): void
/**
 * Check whether a process is running elevated (admin).
 * Returns `true` if the process has an elevated token.
 */
export declare function isProcessElevated(processId: number): boolean
/**
 * Launch a process elevated (admin) using ShellExecuteExW with "runas" verb.
 * This triggers a UAC prompt. Returns the PID of the spawned process.
 */
export declare function runElevated(executablePath: string, args?: Array<string> | undefined | null, cwd?: string | undefined | null): Promise<number>
export declare function captureScreenshot(elementHandle: string): Promise<Array<number>>
export declare function captureScreenshotToFile(elementHandle: string, path: string): Promise<void>
export interface ImageMatch {
  x: number
  y: number
  width: number
  height: number
  confidence: number
}
export declare function findImage(elementHandle: string, template: Array<number>): Promise<ImageMatch | null>
export declare function expandCollapseExpand(elementHandle: string): void
export declare function expandCollapseCollapse(elementHandle: string): void
export declare function scrollPatternScroll(elementHandle: string, horizontalAmount: number, verticalAmount: number): void
export declare function scrollPatternSetScrollPercent(elementHandle: string, horizontalPercent: number, verticalPercent: number): void
export declare function rangeValueGetValue(elementHandle: string): Promise<number>
export declare function rangeValueSetValue(elementHandle: string, value: number): Promise<void>
export declare function windowPatternSetVisualState(elementHandle: string, state: number): void
export declare function windowPatternWaitForInputIdle(elementHandle: string, timeoutMs: number): boolean
export declare function selectionGetSelection(elementHandle: string): Array<string>
