/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'win-auto-native.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.android-arm64.node')
          } else {
            nativeBinding = require('win-auto-native-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'win-auto-native.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.android-arm-eabi.node')
          } else {
            nativeBinding = require('win-auto-native-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'win-auto-native.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('win-auto-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'win-auto-native.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('win-auto-native-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'win-auto-native.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('win-auto-native-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'win-auto-native.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./win-auto-native.darwin-universal.node')
      } else {
        nativeBinding = require('win-auto-native-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'win-auto-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.darwin-x64.node')
          } else {
            nativeBinding = require('win-auto-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'win-auto-native.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.darwin-arm64.node')
          } else {
            nativeBinding = require('win-auto-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'win-auto-native.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./win-auto-native.freebsd-x64.node')
      } else {
        nativeBinding = require('win-auto-native-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-x64-musl.node')
            } else {
              nativeBinding = require('win-auto-native-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-x64-gnu.node')
            } else {
              nativeBinding = require('win-auto-native-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-arm64-musl.node')
            } else {
              nativeBinding = require('win-auto-native-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('win-auto-native-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('win-auto-native-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('win-auto-native-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('win-auto-native-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'win-auto-native.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./win-auto-native.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('win-auto-native-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'win-auto-native.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./win-auto-native.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('win-auto-native-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { setAppConfig, findDialogs, getDialogControls, clickDialogButton, setDialogFilePath, debugDiscovery, inspectHwndTree, waitForUiChange, startWinEventWatcher, stopWinEventWatcher, highlightElement, findElement, typeText, sendKeys, pressKeyCodes, getText, findElementName, clickElement, clickElementByName, clickSequence, buildElementPath, resolveElementPath, hoverElement, scrollElement, getValue, setValue, selectElement, toggleElement, getToggleState, findAll, getParent, getChildren, getSiblings, isVisible, isEnabled, isFocused, focusElement, getWindowBounds, setWindowBounds, focusWindow, maximizeWindow, minimizeWindow, restoreWindow, pressKey, rightClickElement, doubleClickElement, mouseMove, clickAt, keyDown, keyUp, selectText, getSelection, replaceSelectedText, inspectWindowTree, getElementAttribute, dragDrop, launch, ping, enumerateWindows, closeApp, closeWindow, isProcessRunning, findProcessesByName, waitForProcessExit, getProcessImageName, killProcess, captureScreenshot, captureScreenshotToFile, findImage } = nativeBinding

module.exports.setAppConfig = setAppConfig
module.exports.findDialogs = findDialogs
module.exports.getDialogControls = getDialogControls
module.exports.clickDialogButton = clickDialogButton
module.exports.setDialogFilePath = setDialogFilePath
module.exports.debugDiscovery = debugDiscovery
module.exports.inspectHwndTree = inspectHwndTree
module.exports.waitForUiChange = waitForUiChange
module.exports.startWinEventWatcher = startWinEventWatcher
module.exports.stopWinEventWatcher = stopWinEventWatcher
module.exports.highlightElement = highlightElement
module.exports.findElement = findElement
module.exports.typeText = typeText
module.exports.sendKeys = sendKeys
module.exports.pressKeyCodes = pressKeyCodes
module.exports.getText = getText
module.exports.findElementName = findElementName
module.exports.clickElement = clickElement
module.exports.clickElementByName = clickElementByName
module.exports.clickSequence = clickSequence
module.exports.buildElementPath = buildElementPath
module.exports.resolveElementPath = resolveElementPath
module.exports.hoverElement = hoverElement
module.exports.scrollElement = scrollElement
module.exports.getValue = getValue
module.exports.setValue = setValue
module.exports.selectElement = selectElement
module.exports.toggleElement = toggleElement
module.exports.getToggleState = getToggleState
module.exports.findAll = findAll
module.exports.getParent = getParent
module.exports.getChildren = getChildren
module.exports.getSiblings = getSiblings
module.exports.isVisible = isVisible
module.exports.isEnabled = isEnabled
module.exports.isFocused = isFocused
module.exports.focusElement = focusElement
module.exports.getWindowBounds = getWindowBounds
module.exports.setWindowBounds = setWindowBounds
module.exports.focusWindow = focusWindow
module.exports.maximizeWindow = maximizeWindow
module.exports.minimizeWindow = minimizeWindow
module.exports.restoreWindow = restoreWindow
module.exports.pressKey = pressKey
module.exports.rightClickElement = rightClickElement
module.exports.doubleClickElement = doubleClickElement
module.exports.mouseMove = mouseMove
module.exports.clickAt = clickAt
module.exports.keyDown = keyDown
module.exports.keyUp = keyUp
module.exports.selectText = selectText
module.exports.getSelection = getSelection
module.exports.replaceSelectedText = replaceSelectedText
module.exports.inspectWindowTree = inspectWindowTree
module.exports.getElementAttribute = getElementAttribute
module.exports.dragDrop = dragDrop
module.exports.launch = launch
module.exports.ping = ping
module.exports.enumerateWindows = enumerateWindows
module.exports.closeApp = closeApp
module.exports.closeWindow = closeWindow
module.exports.isProcessRunning = isProcessRunning
module.exports.findProcessesByName = findProcessesByName
module.exports.waitForProcessExit = waitForProcessExit
module.exports.getProcessImageName = getProcessImageName
module.exports.killProcess = killProcess
module.exports.captureScreenshot = captureScreenshot
module.exports.captureScreenshotToFile = captureScreenshotToFile
module.exports.findImage = findImage
